### ISSUE TITLE
getAddress: can't get Uniswap router address

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/protocol-contracts#103]
Doesn't work:

```
getAddress("uniswapV3Router", "bsc_testnet")
getAddress("uniswapV2Router02", "bsc_testnet")
```

`getNonZetaAddress` works, but I was wondering if it would make sense to refactor `getAddress` to support all possible addresses we have to simplify dev experience. Ideally, it also handles ZRC-20 for ERC-20.

**Comment by lumtis** [comment]
Is it related to https://github.com/zeta-chain/protocol-contracts/issues/103 ?

**Comment by fadeev** [comment]
`getAddress` has been refactored, so no longer relevant.
