### ISSUE TITLE
`withdrawAndCall` - `evm`: allow sending ERC20 and call function

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/protocol-contracts#150]
Depends on https://github.com/zeta-chain/protocol-contracts/issues/149

Allow to call the function while sending the ERC20 to the contract

- Extend the ERC20Custody contract
- Introduce a new contract for it

**Comment by MK-ATMOSFERA** [comment]
[
![Screenshot_2024-05-16-17-53-46-865_com facebook katana-edit](https://github.com/zeta-chain/protocol-contracts/assets/74942317/f0e21e3d-4eeb-4dfe-92c6-7aee1e438d9b)
](url)

**Comment by lumtis** [comment]
No longer considered
