### ISSUE TITLE
Integrating Slither

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/protocol-contracts#165]
Adding Slither: https://github.com/crytic/slither

Adding in the CI as well.

The tool is already installed in app contracts: https://github.com/zeta-chain/app-contracts

**Comment by fadeev** [comment]
@Kali-Decoder please, let me know if I should assign this issue to you.

**Comment by lumtis** [comment]
Right now it can be run manually but the steps are a little bit annoying:
On mac
```
brew install solc-select
brew unlink solidity
brew link --overwrite solc-select
solc-select install 0.8.7
solc-select use 0.8.7
slither contracts/...--solc-args "--allow-paths .,./node_modules" --solc-remaps @openzeppelin=node_modules/@openzeppelin
```
The config for running slither could be optimized as well. End goal would to have a script doing everything

**Comment by Kali-Decoder** [comment]
Yes you can assign me @fadeev

**Comment by fadeev** [comment]
@Kali-Decoder

* add a script that runs Slither in the `scripts` directory. The script should ensure that all software required for Slither to run is installed and that correct version of Solidity is used
* add a script in `package.json` to run the script
* add GitHub workflow to run the script on each PR

**Comment by Kali-Decoder** [comment]
To run the commands mentioned, I'm utilizing a shell script. I can then add the script's run command to the package.json and incorporate it into the PR workflow.

**Comment by fadeev** [comment]
@Kali-Decoder please, update on progress.

**Comment by fadeev** [comment]
@Kali-Decoder please, update on progress or let me know if I can re-assign this issue. Thank you.

**Comment by fadeev** [comment]
@Kali-Decoder the deadline for this issue is Sunday evening UTC. If you're blocked on something, please, share it here.

**Comment by Kali-Decoder** [comment]
okay @fadeev
