### ISSUE TITLE
Add gas profiling tool

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/protocol-contracts#168]
Add tool to measure contracts gas consumption.

It seems `hardhat-gas-reporter` is present in `package.json` but not used.

**Comment by fadeev** [comment]
@Kali-Decoder please, let me know if I should assign this issue to you.

**Comment by lumtis** [comment]
> @Kali-Decoder please, let me know if I should assign this issue to you.

Was actually very trivial: https://github.com/zeta-chain/protocol-contracts/pull/169
