### ISSUE TITLE
Add zeta consumer address to the Connector contract

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/protocol-contracts#28]
Right now when we deploy a CCM contract we pass three addresses: connector, zeta token, and zeta consumer.

https://github.com/zeta-chain/example-contracts/blob/2c7885cce941d9a02cb4c23324ec9c75e86dee89/messaging/message/contracts/CrossChainMessage.sol#L33-L35

The connector contract already stores the zeta token address as a value:

https://github.com/zeta-chain/protocol-contracts/blob/1b00239471377bc6febb44de7230c006f0c9f5b9/contracts/evm/ZetaConnector.base.sol#L16-L32

Let's refactor the Connector to also store the zeta consumer address.

The improvement will be that users will only have to pass the connector address when deploying a CCM contract, and the contract itself would get zeta token and zeta consumer from the connector.

**Comment by lumtis** [comment]
Closing as it pertains to the v1 contracts that will no longer be developed. Feel free to reopen or create new issue if it's still relevant for v2 contracts
