### ISSUE TITLE
Add specs page in the docs

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/protocol-contracts#336]
Example: docs provided for audit

Add similar page as part of the docs so it can be rendered on the website.

We check to give a proper design for the two diagrams.

Preferably let's wait for the audit to complete first as the interface is subject to change.

**Comment by fadeev** [comment]
https://github.com/zeta-chain/docs/pull/433

**Comment by fadeev** [comment]
I think we can have just two docs: inline docs in the contracts (automatically converted into MD files by forge doc and shipped to the docs repo) and manually written docs in the docs repo (PR above is a draft attempt at that).
