### ISSUE TITLE
Store system contract address inside `UniversalContract`

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/protocol-contracts#343]
We're still using system contract to get WZETA/Uniswap contracts addresses:

https://github.com/zeta-chain/example-contracts/blob/main/universal/swap/contracts/Swap.sol#L20-L22

Ideally, it's inherited from `UniversalContract` until we deprecate and remove it in favor of a contract registry.

**Comment by lumtis** [comment]
I think we should rename it, registry or something like this

**Comment by fadeev** [comment]
I've removed system contract from example contracts, so it's no longer going to be used, we don't need to add it anywhere.
