### ISSUE TITLE
Automate generation of `addresses.json`

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/protocol-contracts#88]
I’d like to revisit our conversation about automatically generating the contract address file:

https://github.com/zeta-chain/protocol-contracts/blob/main/data/addresses.json

We have ZRC-20 addresses not added to this file ([BTC](https://github.com/zeta-chain/protocol-contracts/pull/83) and USDC), which is not great. I don’t want anyone to be in charge of keeping the file up to date when a machine can do it instead of us. If there are objections to this, please, do let me know, otherwise, I’m writing a script to automate this.

What I’m proposing:

1. A script runs daily in a GH workflow, queries the chain for contract addresses.
2. If addresses.json is outdated it creates a PR for us.
3. We approve the PR, press “Release” button.

@andresaiello @lucas-janon

**Comment by andresaiello** [comment]
I agree with that

**Comment by fadeev** [comment]
Depends on https://github.com/zeta-chain/protocol-contracts/issues/89

**Comment by fadeev** [comment]
@lucas-janon wdyt?
