### ISSUE TITLE
Add address(0) check for addresses in parameters and constructors

### ISSUE THREAD

**Issue by lukema95** [zeta-chain/protocol-contracts#92]
I think it's necessary to add a check for address(0) in the parameters and constructors, it can make the contract logic more robust. The address(0) check of the address in the parameter can avoid some unnecessary errors. Initializing a state variable with address(0) can lead to unintended behavior and vulnerabilities in the contract.

1. Add address(0) check for addresses in constructors.
https://github.com/zeta-chain/protocol-contracts/blob/86ff71155dac8a10168794886200d989fe254ae0/contracts/zevm/SystemContract.sol#L51

https://github.com/zeta-chain/protocol-contracts/blob/86ff71155dac8a10168794886200d989fe254ae0/contracts/zevm/ConnectorZEVM.sol#L80

https://github.com/zeta-chain/protocol-contracts/blob/86ff71155dac8a10168794886200d989fe254ae0/contracts/zevm/ZRC20.sol#L67

2. Add address(0) check for address in parameters.
check target address
https://github.com/zeta-chain/protocol-contracts/blob/86ff71155dac8a10168794886200d989fe254ae0/contracts/zevm/SystemContract.sol#L71

check erc20 address
https://github.com/zeta-chain/protocol-contracts/blob/86ff71155dac8a10168794886200d989fe254ae0/contracts/zevm/SystemContract.sol#L145

check zrc20 address
https://github.com/zeta-chain/protocol-contracts/blob/86ff71155dac8a10168794886200d989fe254ae0/contracts/zevm/SystemContract.sol#L134

3. Check if the address is a contract.
add `if (target.code.length == 0) revert InvalidTarget();` check
https://github.com/zeta-chain/protocol-contracts/blob/86ff71155dac8a10168794886200d989fe254ae0/contracts/zevm/SystemContract.sol#L71

**Comment by fadeev** [comment]
cc @andresaiello
